# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ImageDownloader.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageDownloader(object):
    def setupUi(self, ImageDownloader):
        ImageDownloader.setObjectName(_fromUtf8("ImageDownloader"))
        ImageDownloader.resize(547, 600)
        ImageDownloader.setMinimumSize(QtCore.QSize(0, 0))
        ImageDownloader.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(ImageDownloader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(801, 561))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, -10, 521, 511))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 521, 501))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Label_Url = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_Url.setFont(font)
        self.Label_Url.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Url.setObjectName(_fromUtf8("Label_Url"))
        self.horizontalLayout.addWidget(self.Label_Url)
        self.LineText_ComicUrl = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.LineText_ComicUrl.setObjectName(_fromUtf8("LineText_ComicUrl"))
        self.horizontalLayout.addWidget(self.LineText_ComicUrl)
        self.PushButton_Enter = QtGui.QPushButton(self.verticalLayoutWidget)
        self.PushButton_Enter.setObjectName(_fromUtf8("PushButton_Enter"))
        self.horizontalLayout.addWidget(self.PushButton_Enter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.TreeView_ComicLists = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.TreeView_ComicLists.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TreeView_ComicLists.setObjectName(_fromUtf8("TreeView_ComicLists"))
        self.TreeView_ComicLists.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_2.addWidget(self.TreeView_ComicLists)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(256, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(12, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(192, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget.raise_()
        self.frame.raise_()
        self.TreeView_ComicLists.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 521, 501))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.TreeView_ComicLists_2 = QtGui.QTreeWidget(self.verticalLayoutWidget_2)
        self.TreeView_ComicLists_2.setMinimumSize(QtCore.QSize(512, 0))
        self.TreeView_ComicLists_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TreeView_ComicLists_2.setObjectName(_fromUtf8("TreeView_ComicLists_2"))
        self.TreeView_ComicLists_2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.TreeView_ComicLists_2)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.progressBar.raise_()
        self.label.raise_()
        self.tabWidget.raise_()
        ImageDownloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(ImageDownloader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ImageDownloader.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ImageDownloader)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ImageDownloader.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(ImageDownloader)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        ImageDownloader.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionNewTask = QtGui.QAction(ImageDownloader)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Milky/Icons/64/112.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNewTask.setIcon(icon)
        self.actionNewTask.setObjectName(_fromUtf8("actionNewTask"))
        self.actionSearch = QtGui.QAction(ImageDownloader)
        self.actionSearch.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Milky/Icons/64/10.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSearch.setIcon(icon1)
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionOptions = QtGui.QAction(ImageDownloader)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Milky/Icons/64/11.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOptions.setIcon(icon2)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionUnselecet_All = QtGui.QAction(ImageDownloader)
        self.actionUnselecet_All.setObjectName(_fromUtf8("actionUnselecet_All"))
        self.actionSelecet_All = QtGui.QAction(ImageDownloader)
        self.actionSelecet_All.setObjectName(_fromUtf8("actionSelecet_All"))
        self.actionDownload = QtGui.QAction(ImageDownloader)
        self.actionDownload.setObjectName(_fromUtf8("actionDownload"))
        self.actionCancel = QtGui.QAction(ImageDownloader)
        self.actionCancel.setObjectName(_fromUtf8("actionCancel"))
        self.toolBar.addAction(self.actionNewTask)
        self.toolBar_2.addAction(self.actionSearch)
        self.toolBar_2.addAction(self.actionOptions)

        self.retranslateUi(ImageDownloader)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageDownloader)

    def retranslateUi(self, ImageDownloader):
        ImageDownloader.setWindowTitle(_translate("ImageDownloader", "ImageDownloader", None))
        self.Label_Url.setText(_translate("ImageDownloader", "Comic url ", None))
        self.PushButton_Enter.setText(_translate("ImageDownloader", "Enter", None))
        self.label.setText(_translate("ImageDownloader", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImageDownloader", "Tab 1", None))
        self.label_2.setText(_translate("ImageDownloader", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImageDownloader", "Tab 2", None))
        self.toolBar.setWindowTitle(_translate("ImageDownloader", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("ImageDownloader", "toolBar_2", None))
        self.actionNewTask.setText(_translate("ImageDownloader", "NewTask", None))
        self.actionSearch.setText(_translate("ImageDownloader", "Search", None))
        self.actionOptions.setText(_translate("ImageDownloader", "Options", None))
        self.actionUnselecet_All.setText(_translate("ImageDownloader", "Unselecet All", None))
        self.actionSelecet_All.setText(_translate("ImageDownloader", "Selecet All", None))
        self.actionDownload.setText(_translate("ImageDownloader", "Download", None))
        self.actionCancel.setText(_translate("ImageDownloader", "Cancel", None))

#import umleditor_rc
